language: python
os:
  - linux
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy"
install:
  - "pip install flake8"
  - "pip install -r requirements.txt"
before_script:
  - "flake8 ."
script:
  - py.test tests # or pytest for Python versions 3.6 and above
