language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements.txt
script:
  - py.test tests --runslow # or pytest for Python versions 3.6 and above
os:
  - linux
