sudo: false

language: python

matrix:
  include:
    - python: 2.7
      dist: trusty
    - python: 3.5
      dist: trusty
    - python: 3.6
      dist: trusty
    - python: 3.7
      dist: xenial
      sudo: true


install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - python setup.py install

script:
  - flake8 --version
  - flake8 SECEdgar
  - pytest SECEdgar/tests
